version: "3"

tasks:
  setup:
    - python3 -m venv .venv
    - .venv/bin/pip install -r requirements.txt
    - .venv/bin/pre-commit install
    - .venv/bin/dbt deps
    - npm install --prefix ./reports
  extract:
    cmds:
      - .venv/bin/python el.py -e {{.start}} {{.end}}
  load:
    cmds:
      - .venv/bin/python el.py -l {{.start}} {{.end}}
  load-prod:
    cmds:
      - .venv/bin/python el.py -lp {{.start}} {{.end}}
  el-prod-incremental:
    cmds:
      - .venv/bin/python el.py -elpi {{.start}} {{.end}}
  transform:
    cmds:
      - .venv/bin/dbt build
  transform-prod:
    cmds:
      - .venv/bin/dbt build --target prod
  elt:
    cmds:
      - .venv/bin/python el.py -eli {{.start}} {{.end}}
      - .venv/bin/dbt build
  elt-prod:
    cmds:
      - .venv/bin/python el.py -elpi {{.start}} {{.end}}
      - .venv/bin/dbt build --target prod
  bi:
    cmds:
      - npm run dev --prefix ./reports
  clean:
    cmds:
      - rm -f ./data/*.json.gz 2>/dev/null; exit 0
  generate-fixtures:
    cmds:
      - .venv/bin/python el.py -e 2023-09-26-10 2023-09-26-10
      - duckdb < generate_fixtures.sql
      - rm ./data/2023-09-26-10.json.gz
